---
title: "ACTSeq Clustering all marks"
author: "Marlene Ganslmeier"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
 # html_notebook: default
  workflowr::wflow_html:
    toc: true
    toc_depth: 2
    code_folding: "hide"
    toc_float: true
    fig_width: 10
    fig_height: 7
#output: workflowr::wflow_html:
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)


library(data.table)
library(ggplot2)
library(ggsignif)
library(ggpubr)
library(tidyr)
library(pheatmap)
library(viridis)
library(GenomicRanges)
library(gUtils)
library(ComplexHeatmap)
library(reshape2)
library(hexbin)
library(RColorBrewer)
library(dplyr)
library(plotly)
library(htmlwidgets)
library(cowplot)
library(purrr)

```

# 10Kb binning

```{r results='asis'}

H3K9me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K9me3_mbw_summary_10kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K27me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K27me3_mbw_summary_10kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K36me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K36me3_mbw_summary_10kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K27ac <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K27ac_mbw_summary_10kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

data <- merge(H3K9me3, H3K27me3, all = TRUE)
data <- merge(data, H3K36me3, all = TRUE)
data <- merge(data, H3K27ac, all = TRUE)


#filter out bad reads
data<-data[-grep("chrM|chrUn|_random|_gl|dbb|_hap", data[,1]),]

#tidy data
coords<-data[,1:3]
colnames(coords)<-c("chr", "start", "end")
data<-data[,-c(1:3)]
data<-apply(data, 2, as.numeric)


#construct GRanges Object
windows_full<-GenomicRanges:::GRanges(coords[,1], IRanges:::IRanges(coords[,2],coords[,3]), "*")
mcols(windows_full)<-data

windows <- windows_full
wt_samples <- c("KH2wt")
mt_samples <- c("KH2G34R", "KH2G34W", "KH2G34L")
tab<-as.data.frame(mcols(windows))

### heatmap
N_TOP<-20000
    
sampls_mark<-sapply(strsplit(split="_",colnames(data)), "[", 1)
histone_mark<-sapply(strsplit(split="_",colnames(data)), "[", 2)


data_log<-log2(data)
    
data[data_log==-Inf]<-0
rowsd<-apply(data_log, 1, sd)
top_rows<-order(-rowsd)[seq(N_TOP)]

top_mat<-data_log[top_rows,]

QUANT<-0.01
zlim <- quantile(top_mat, c(QUANT,1-QUANT), na.rm=TRUE)
zmin<-zlim[1]
zmax<-zlim[2]
top_mat[top_mat>zmax]<-zmax
top_mat[top_mat<zmin]<-zmin

col_annot <- data.frame(H3F3A=c("WT","MT")[1+(sampls_mark%in% mt_samples)],                         Sample=sapply(strsplit(split="_",colnames(top_mat)), "[", 1), 
                        histone_mark=sapply(strsplit(split="_",colnames(data)), "[", 2))
    
rownames(col_annot)<-colnames(top_mat)
colors <- list(H3F3A=c(MT = "#A72608", WT = "#79B791"),
               Sample=c(KH2G34L = "#DDD78D", KH2G34R = "#693668",
                        KH2G34W = "#FF8C61", KH2wt = "#FFD046"),
               histone_mark=c(H3K9me3 = "#60992D",H3K27me3 = "#C5D6D8",
                              H3K36me3 = "#30323D", H3K27ac = "#DE8F6E"))
 
pheatmap(top_mat,
         annotation_col=col_annot,
         annotation_colors = colors,
         labels_col = paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                             sapply(strsplit(split="_",colnames(data)), "[", 2)),
         clustering_distance_cols="correlation")

mat<-cor(tab, method="pearson", use="pairwise.complete.obs")

#hc = hclust(as.dist(1 - mat))
#mat = mat[hc$order, hc$order]
#mat[upper.tri(mat)] = NA

breaksList<-seq(min(mat, na.rm = T),1, by=0.05)

p <- pheatmap(mat,
        color = colorRampPalette(RColorBrewer:::brewer.pal(n = 7, name="YlGnBu"))(length(breaksList)+1),
        breaks = breaksList,
        annotation_col=col_annot,
        annotation_colors = colors,
        scale="none",
        cluster_cols=T,
        cluster_rows=T,
        na_col="white",
        labels_row=paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                          sapply(strsplit(split="_",colnames(data)), "[", 2)),
        labels_col = paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                            sapply(strsplit(split="_",colnames(data)), "[", 2)),
        show_rownames=TRUE, show_colnames=TRUE,
        display_numbers=FALSE, number_format="%.2f")
```

# 1Kb binning

```{r results='asis'}

H3K9me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K9me3_mbw_summary_1kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K27me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K27me3_mbw_summary_1kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K36me3 <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K36me3_mbw_summary_1kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

H3K27ac <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/New/matrix/H3K27ac_mbw_summary_1kb_cwlab_wfl.mat", stringsAsFactors=FALSE, header=TRUE, comment.char="!")

data <- merge(H3K9me3, H3K27me3, all = TRUE)
data <- merge(data, H3K36me3, all = TRUE)
data <- merge(data, H3K27ac, all = TRUE)


#filter out bad reads
data<-data[-grep("chrM|chrUn|_random|_gl|dbb|_hap", data[,1]),]

#tidy data
coords<-data[,1:3]
colnames(coords)<-c("chr", "start", "end")
data<-data[,-c(1:3)]
data<-apply(data, 2, as.numeric)


#construct GRanges Object
windows_full<-GenomicRanges:::GRanges(coords[,1], IRanges:::IRanges(coords[,2],coords[,3]), "*")
mcols(windows_full)<-data

windows <- windows_full
wt_samples <- c("KH2wt")
mt_samples <- c("KH2G34R", "KH2G34W", "KH2G34L")
tab<-as.data.frame(mcols(windows))

### heatmap
N_TOP<-20000
    
sampls_mark<-sapply(strsplit(split="_",colnames(data)), "[", 1)
histone_mark<-sapply(strsplit(split="_",colnames(data)), "[", 2)


data_log<-log2(data)
    
data[data_log==-Inf]<-0
data[data_log==Inf]<-0

rowsd<-apply(data_log, 1, sd)
top_rows<-order(-rowsd)[seq(N_TOP)]
top_mat<-data_log[top_rows,]

QUANT<-0.01
zlim <- quantile(top_mat, c(QUANT,1-QUANT), na.rm=TRUE)
zmin<-zlim[1]
zmax<-zlim[2]

top_mat[top_mat>zmax]<-zmax
top_mat[top_mat<zmin]<-zmin

top_mat <- na.omit(top_mat)

#not exactly sure why I need this here

top_mat[which(!is.finite(top_mat))] <- 0

col_annot <- data.frame(H3F3A=c("WT","MT")[1+(sampls_mark%in% mt_samples)],                         Sample=sapply(strsplit(split="_",colnames(top_mat)), "[", 1), 
                        histone_mark=sapply(strsplit(split="_",colnames(data)), "[", 2))
    
rownames(col_annot)<-colnames(top_mat)
colors <- list(H3F3A=c(MT = "#A72608", WT = "#79B791"),
               Sample=c(KH2G34L = "#DDD78D", KH2G34R = "#693668",
                        KH2G34W = "#FF8C61", KH2wt = "#FFD046"),
               histone_mark=c(H3K9me3 = "#60992D",H3K27me3 = "#C5D6D8",
                              H3K36me3 = "#30323D", H3K27ac = "#DE8F6E"))
 
pheatmap(top_mat,
         annotation_col=col_annot,
         annotation_colors = colors,
         labels_col = paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                             sapply(strsplit(split="_",colnames(data)), "[", 2)),
         clustering_distance_cols="correlation")

mat<-cor(tab, method="pearson", use="pairwise.complete.obs")

breaksList<-seq(min(mat, na.rm = T),1, by=0.05)

p <- pheatmap(mat,
        color = colorRampPalette(RColorBrewer:::brewer.pal(n = 7, name="YlGnBu"))(length(breaksList)+1),
        breaks = breaksList,
        annotation_col=col_annot,
        annotation_colors = colors,
        scale="none",
        cluster_cols=T,
        cluster_rows=T,
        na_col="white",
        labels_row=paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                          sapply(strsplit(split="_",colnames(data)), "[", 2)),
        labels_col = paste0(sapply(strsplit(split="_",colnames(data)), "[", 1),
                            sapply(strsplit(split="_",colnames(data)), "[", 2)),
        show_rownames=TRUE, show_colnames=TRUE,
        display_numbers=FALSE, number_format="%.2f")
```
