---
title: "ACTSeq H3K9me3 mouse ESC"
author: "Marlene Ganslmeier"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
 # html_notebook: default
  workflowr::wflow_html:
    toc: true
    toc_depth: 2
    code_folding: "hide"
    toc_float: true
    fig_width: 10
    fig_height: 7
#output: workflowr::wflow_html:
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)


library(data.table)
library(ggplot2)
library(ggsignif)
library(ggpubr)
library(tidyr)
library(pheatmap)
library(viridis)
library(GenomicRanges)
library(gUtils)
library(ComplexHeatmap)
library(reshape2)
library(RnBeads)
library(hexbin)
library(RColorBrewer)
library(dplyr)
library(RnBeads.hg19)
library(plotly)
library(htmlwidgets)
library(cowplot)


binnedMean <- function(bins, numvar, mcolname)
{
    stopifnot(is(bins, "GRanges"))
    stopifnot(is(numvar, "RleList"))
    stopifnot(identical(seqlevels(bins), names(numvar)))
    bins_per_chrom <- split(ranges(bins), seqnames(bins))
    sums_list <- lapply(names(numvar),
            function(seqname) {
                views <- Views(numvar[[seqname]],
                        bins_per_chrom[[seqname]])
                viewMeans(views)
            })
    new_mcol <- unsplit(sums_list, as.factor(seqnames(bins)))
    mcols(bins)[[mcolname]] <- new_mcol
    bins
}

binnedSum <- function(bins, numvar, mcolname)
{
    stopifnot(is(bins, "GRanges"))
    stopifnot(is(numvar, "RleList"))
    stopifnot(identical(seqlevels(bins), names(numvar)))
    bins_per_chrom <- split(ranges(bins), seqnames(bins))
    sums_list <- lapply(names(numvar),
            function(seqname) {
                views <- Views(numvar[[seqname]],
                        bins_per_chrom[[seqname]])
                viewSums(views)
            })
    new_mcol <- unsplit(sums_list, as.factor(seqnames(bins)))
    mcols(bins)[[mcolname]] <- new_mcol
    bins
}

calcDiff <- function(input, what)
{
  
if(what == "Delta"){  
  #calculate delta
vector <- input[input$Group=="MT", "avg_value"]-input[input$Group=="WT", "avg_value"]
#sub for MT
vector_dd <-input[input$Group=="MT",]
#replace MT with Delta
vector_dd$Group<-rep(what,nrow(vector_dd))
#replace MT value with Delta value
vector_dd$avg_value<-vector$avg_value
#append to dataset
input<-rbind(input, vector_dd)
input <- na.omit(input)
return(input)
}
  else if(what =="LFC"){
    
      #calculate LFC
vector <- log2(input[input$Group=="MT", "avg_value"]+1)-log2(input[input$Group=="WT", "avg_value"]+1)
#sub for MT
vector_dd <-input[input$Group=="MT",]
#replace MT with Delta
vector_dd$Group<-rep(what,nrow(vector_dd))
#replace MT value with Delta value
vector_dd$avg_value<-vector$avg_value
#append to dataset
input<-rbind(input, vector_dd)
input <- na.omit(input)
return(input)
    
  }
}

```

```{r eval = F}
library(rtracklayer)
library(regioneR)

chmm_segments <- toGRanges("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/mESC_E14_12_dense.annotated.bed")

segments <- unique(chmm_segments@elementMetadata@listData[["name"]])

mmchmm_list <- list()
for(i in segments){
mmchmm_list[[i]] <- chmm_segments[(elementMetadata(chmm_segments)[, "name"] == i)]
}
saveRDS(mmchmm_list, "data/chmm_mESC.rds")

```

```{r}
chmm_segments<-readRDS(file="data/chmm_mESC.rds")

#chmm_segments_mESC <- read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/mESC_E14_12_dense.annotated.bed", header = FALSE, sep="\t",stringsAsFactors=FALSE, fill = T, skip = 0)

#library("regioneR")

#chmm_segments <- toGRanges("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/mESC_E14_12_dense.annotated.bed")
```

```{r}
#read in matrix from multiBigWigSummary

data <-read.table("/omics/groups/OE0219/internal/ganslm/Analysis/Mouse_ActSeq/all_marks_mbw_summary_1kb_RPKM.mat",
        stringsAsFactors=FALSE, header=TRUE, comment.char="!")

#filter out bad reads
data<-data[-grep("chrM|chrUn|_random|_gl|dbb|_hap", data[,1]),]

#tidy data
coords<-data[,1:3]
colnames(coords)<-c("chr", "start", "end")
data<-data[,-c(1:3)]
data<-apply(data, 2, as.numeric)

#construct GRanges Object
windows_full<-GenomicRanges:::GRanges(coords[,1], IRanges:::IRanges(coords[,2],coords[,3]), "*")
mcols(windows_full)<-data

tile1kb <- gr.tile(windows_full, 1000)

windows <- windows_full

tab<-as.data.frame(mcols(windows))

mt_samples<-c("KH2G34L","KH2G34R","KH2G34W")

wt_samples<-c("KH2wt")
```

```{r eval = TRUE}
### heatmap
N_TOP<-20000
    
    sampls_mark<-sapply(strsplit(split="_",colnames(data)), "[", 1)

    data_log<-log2(data)
    
    #I get -Inf instead of pos Inf
    data[data_log==-Inf]<-0

    rowsd<-apply(data_log, 1, sd)
    top_rows<-order(-rowsd)[seq(N_TOP)]

    top_mat<-data_log[top_rows,]

    QUANT<-0.01
    zlim <- quantile(top_mat, c(QUANT,1-QUANT), na.rm=TRUE)
    zmin<-zlim[1]
    zmax<-zlim[2]
    top_mat[top_mat>zmax]<-zmax
    top_mat[top_mat<zmin]<-zmin

    col_annot<-data.frame(H3F3A=c("WT","MT")[1+(sampls_mark%in% mt_samples)], SampleID=colnames(top_mat))
    
rownames(col_annot)<-col_annot$SampleID

pheatmap(top_mat,
            annotation_col=col_annot,
            clustering_distance_cols="correlation")



###### recalculate averages

averages_wt<- rowMeans(tab[,grep(paste(wt_samples, collapse="|"), colnames(tab))])
averages_mut<- rowMeans(tab[,grep(paste(mt_samples, collapse="|"), colnames(tab))])

coords_avg<-coords
avg_tab<-cbind(averages_wt, averages_mut)
avg_tab[avg_tab<0]<-0

avg_tab<-log2(avg_tab)
avg_tab[avg_tab<0]<-0


############## CALCULATE DELTAS
avg_tab <- as.data.frame(avg_tab)
delta <- avg_tab$averages_wt - avg_tab$averages_mut

### assign values to chip_windows
mcols(windows)<-cbind(avg_tab, delta)

############### CORRELATIONS

corr_all<-cor(avg_tab, method="pearson")
rownames(corr_all)<-gsub("average", "", rownames(corr_all))
colnames(corr_all)<-gsub("average", "", colnames(corr_all))

tab_log<-log2(tab)
tab_log[tab_log<0]<-0

corr_all_raw<-cor(tab, method="pearson", use="pairwise.complete.obs")


breaksList<-seq(0.3,1, by=0.05)

p <- pheatmap(corr_all_raw,
        color = colorRampPalette(RColorBrewer:::brewer.pal(n = 7, name ="YlGnBu"))(length(breaksList)+1),
        breaks = breaksList,
        scale="none",cluster_cols=FALSE,cluster_rows=FALSE,
        show_rownames=TRUE, show_colnames=TRUE,
        display_numbers=TRUE, number_format="%.2f")

```

```{r eval = TRUE}
#as ggplot


  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  
  upper_tri <- get_upper_tri(corr_all_raw)

melted_cormat <- reshape2::melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
  
  
```

```{r eval=TRUE}

#### ALTERNATIVELY USE THE PACKAGE GUTILS

target_window_list <- chmm_segments
target_windows_int<-lapply(target_window_list, "mcols<-", value=NULL)
summ_windows<-lapply(target_windows_int, function(pkl) pkl %$% windows_full)

summ_windows<-lapply(names(summ_windows), function(nn) {x=summ_windows[[nn]]; x$Feature<-rep(nn, "_", length(summ_windows[[nn]]));x})
names(summ_windows)<-names(target_windows_int)
summ_windows<-lapply(names(summ_windows), function(nn) {x=summ_windows[[nn]]; x$Region<-paste0(nn, "_", seq(summ_windows[[nn]]));x})
names(summ_windows)<-names(target_windows_int)

full_data<-as.data.frame(do.call("rbind",lapply(summ_windows, mcols)))
full_data<-gather(full_data, key="Stat", value="value", -Feature, -Region)
full_data$Sample<-sapply(strsplit(full_data$Stat, split="_"),"[",1)
full_data$Mark<-sapply(strsplit(full_data$Stat, split="_"),"[",2)
full_data$Group<-c("WT","MT")[(full_data$Sample %in% mt_samples)+1]

full_data$Sample<-factor(full_data$Sample, levels=c(wt_samples, mt_samples))
full_data$Feature<-factor(full_data$Feature,levels=names(target_windows_int))

full_data$log2_value<-log2(full_data$value+1)


full_data<-na.omit(full_data)

sum_full_data<-full_data %>% 
    group_by(Group,Mark,Region,Feature, Sample)%>% 
    dplyr::summarize(avg_value=mean(value))

samples <- unique(sum_full_data$Sample)
samples <- samples[1:3]

#calcDiff returns input
#it's very not elegant but it gets the job done - for a bigger dataset with more marks I gotta come up with an automisation
for(i in samples){
  print(i)
  interim <- sum_full_data%>%
  filter(Sample == "KH2wt" | Sample == i)
  
  interim <- calcDiff(interim, "Delta")
  interim <- calcDiff(interim, "LFC")
  
  assign(paste0("data_", i), interim)
}

sum_full_data <- rbind(data_KH2G34L, data_KH2G34R, data_KH2G34W)


######### PLOT THE SUMMARIZED DATA II

npg_pal<-ggsci:::pal_npg()
npg_cols<-c(npg_pal(10)[c(1,4,8)], "black")


#### BOXPLOT PER GROUP
```

## Boxplots {.tabset .tabset-fade .tabset-pills}

```{r eval=TRUE, results='asis'}

for(i in 1:length(mt_samples)){
      cat('\n')
      cat("###",mt_samples[i], "\n")

  data <- sum_full_data %>%
  filter(Sample == wt_samples[1] | Sample == mt_samples[i])
  
p <-ggpubr:::ggboxplot(data, x="Feature", y= "avg_value", color="Group", 
                palette=npg_cols)+
  facet_wrap(c("Group"), scales="fixed", nrow = 1)+
  rotate_x_text(angle = 90, hjust = NULL, vjust = 0)

print(p)

      cat('\n')

 }

```

```{r}
npg_pal<-ggsci:::pal_npg()
grad_cols1<-npg_pal(10)[c(4,1)]

mat_pal<-ggsci:::pal_material("orange")
grad_cols2<-mat_pal(10)[c(1,10)]

mat_pal<-ggsci:::pal_material("indigo")
grad_cols3<-mat_pal(10)[c(1,10)]

grad_cols<-c(grad_cols3[2], grad_cols2[2])
mut_wt_cols<-npg_pal(10)[c(4,1)]


sums <- sum_full_data %>%
  group_by(Feature, Group, Sample)%>%
  summarise(mean = mean(avg_value))
```

## Heatmaps {.tabset .tabset-fade .tabset-pills}

### Delta
```{r results='asis'}
########plot summarized data I

plot_Delta <- sums %>%
 filter(Group == "Delta")%>%
 # group_by(Feature, Group)%>%
  #summarise(mean = mean(mean))%>% #needed to fix colour gradient
  ggplot(aes(Feature))+
  geom_tile(aes_string(x="Feature", y = "1", fill = "mean"), size = 1)+
  scale_fill_gradient2(low=grad_cols[1], mid="white", high=grad_cols[2])+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 60, size = 10, face = "bold", hjust = 1),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  facet_wrap(~Sample, nrow = 3)+
  theme(strip.background=element_rect(fill="white"))

print(plot_Delta)
```

### LFC
```{r results='asis'}
plot_LFC <- sums %>%
 filter(Group == "LFC")%>%
 # group_by(Feature, Group)%>%
  #summarise(mean = mean(mean))%>% #needed to fix colour gradient
  ggplot(aes(Feature))+
  geom_tile(aes_string(x="Feature", y = "1", fill = "mean"), size = 1)+
  scale_fill_gradient2(low=grad_cols[1], mid="white", high=grad_cols[2])+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 60, size = 10, face = "bold", hjust = 1),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  facet_wrap(~Sample, nrow = 3)+
  theme(strip.background=element_rect(fill="white"))

print(plot_LFC)

```


## Seperate Violin Plots of Features {.tabset .tabset-fade .tabset-pills}

```{r results='asis'}
features <- sum_full_data %>%
  group_by(Feature)%>%
  filter(Group =="WT"|Group =="MT")%>%
  group_split()

for(i in 1:length(features)){
      cat('\n')
    cat("###", features[[i]]$Feature[1], "\n")

  p <- ggplot(features[[i]], aes(x=Sample, y = avg_value))+
        geom_violin()+
    labs(title = features[[i]]$Feature )
    print(p)
        cat('\n')

 }


```

##  {.unnumbered}
